---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: openvswitch
tags: [networking, vswitch, bridge, vlan]
namespace: openvswitch
readme: README.md
repository: https://github.com/ansible-collections/openvswitch.openvswitch
version: 1.1.1
